export const ONE_THREAD_REQUEST_SUCCESS = 'ONE_THREAD_REQUEST_SUCCESS';

export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const MODULE_REQUEST_SUCCESS = 'MODULE_REQUEST_SUCCESS';
export const MODULE_YEARS_SEMS_REQUEST_SUCCESS = 'MODULE_YEARS_SEMS_REQUEST_SUCCESS';
export const PAPERS_REQUEST_SUCCESS = 'PAPERS_REQUEST_SUCCESS';
export const THREADS_REQUEST_SUCCESS = 'THREADS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
export const CREATE_MODULE_REQUEST = 'CREATE_TOPIC_REQUEST';

export const NUS_LOGIN_SUCCESS = 'NUS_LOGIN_SUCCESS';
export const FETCH_MODULE_LIST = 'FETCH_MODULE_LIST';
export const VALIDATE = 'VALIDATE';
export const FETCH_LAPI_SUCCESS = 'FETCH_LAPI_SUCCESS';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
